name: mansa
description: Flutter authentication and subscription app with Arabic RTL support

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  url_launcher: ^6.1.10
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
